"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _kpi_cards from './kpi-cards.bones.json'
import _analytics_chart from './analytics-chart.bones.json'
import _recent_transactions from './recent-transactions.bones.json'

registerBones({
  "kpi-cards": _kpi_cards,
  "analytics-chart": _analytics_chart,
  "recent-transactions": _recent_transactions,
})
