import type { Charge } from "./payment-types";

const now = Math.floor(Date.now() / 1000);
const DAY = 86_400;

export const MOCK_CHARGES: Charge[] = [
  {
    id: "ch_001abc",
    amount: 4999,
    currency: "EUR",
    status: "SUCCEEDED",
    createdAt: now - DAY * 0,
    updatedAt: now - DAY * 0,
    orderId: "order_001",
    livemode: false,
    customer: { name: "Ana García", email: "ana@example.com" },
    paymentMethod: { method: "card", card: { brand: "visa", last4: "4242", expMonth: 12, expYear: 2026 } },
    description: "Pro subscription",
  },
  {
    id: "ch_002def",
    amount: 1299,
    currency: "EUR",
    status: "FAILED",
    createdAt: now - DAY * 1,
    updatedAt: now - DAY * 1,
    orderId: "order_002",
    livemode: false,
    customer: { name: "Carlos López", email: "carlos@example.com" },
    paymentMethod: { method: "card", card: { brand: "mastercard", last4: "5555", expMonth: 8, expYear: 2025 } },
    statusCode: "E101",
    statusMessage: "Insufficient funds",
  },
  {
    id: "ch_003ghi",
    amount: 24900,
    currency: "EUR",
    status: "REFUNDED",
    createdAt: now - DAY * 2,
    updatedAt: now - DAY * 1,
    orderId: "order_003",
    livemode: false,
    customer: { name: "Maria Costa", email: "maria@example.com" },
    paymentMethod: { method: "bizum" },
    description: "Annual plan",
  },
  {
    id: "ch_004jkl",
    amount: 799,
    currency: "EUR",
    status: "PENDING",
    createdAt: now - DAY * 3,
    updatedAt: now - DAY * 3,
    livemode: false,
    paymentMethod: { method: "card", card: { brand: "visa", last4: "1111", expMonth: 3, expYear: 2027 } },
  },
  {
    id: "ch_005mno",
    amount: 9900,
    currency: "EUR",
    status: "SUCCEEDED",
    createdAt: now - DAY * 4,
    updatedAt: now - DAY * 4,
    orderId: "order_005",
    livemode: false,
    customer: { name: "Pedro Martínez", email: "pedro@example.com" },
    paymentMethod: { method: "card", card: { brand: "amex", last4: "0005", expMonth: 11, expYear: 2028 } },
    metadata: [{ key: "plan", value: "business" }, { key: "seats", value: "5" }],
  },
  {
    id: "ch_006pqr",
    amount: 3500,
    currency: "EUR",
    status: "CANCELED",
    createdAt: now - DAY * 5,
    updatedAt: now - DAY * 5,
    livemode: false,
    paymentMethod: { method: "sepa" },
  },
  {
    id: "ch_007stu",
    amount: 14900,
    currency: "EUR",
    status: "SUCCEEDED",
    createdAt: now - DAY * 6,
    updatedAt: now - DAY * 6,
    orderId: "order_007",
    livemode: false,
    customer: { name: "Laura Fernández", email: "laura@example.com" },
    paymentMethod: { method: "card", card: { brand: "visa", last4: "9999", expMonth: 7, expYear: 2026 } },
  },
  {
    id: "ch_008vwx",
    amount: 2000,
    currency: "EUR",
    status: "AUTHORIZED",
    createdAt: now - DAY * 7,
    updatedAt: now - DAY * 7,
    livemode: false,
    paymentMethod: { method: "card", card: { brand: "mastercard", last4: "3333", expMonth: 1, expYear: 2027 } },
  },
];
